In [17]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import fetch_openml
from sklearn.model_selection import train_test_split
%matplotlib inline

In [2]:
def step_func(x):
    y = x > 0
    return y.astype(int)

def sigmoid(x):
    y = 1 / (1 + np.exp(-x))
    return y

def relu(x):
    return np.maximum(0, x)

def identity_func(x):
    return x

In [3]:
def init_network():
    network = {}
    network['W1'] = np.array([[0.1, 0.3, 0.5], [0.2, 0.4, 0.6]])
    network['b1'] = np.array([0.1, 0.2, 0.3])
    network['W2'] = np.array([[0.3, 0.4], [0.5, 0.6], [0.7, 0.8]])
    network['b2'] = np.array([0.2, 0.3])
    network['W3'] = np.array([[0.6, 0.5], [0.4, 0.3]])
    network['b3'] = np.array([0.2, 0.1])

    return network

In [4]:
init_network()

{'W1': array([[0.1, 0.3, 0.5],
        [0.2, 0.4, 0.6]]),
 'b1': array([0.1, 0.2, 0.3]),
 'W2': array([[0.3, 0.4],
        [0.5, 0.6],
        [0.7, 0.8]]),
 'b2': array([0.2, 0.3]),
 'W3': array([[0.6, 0.5],
        [0.4, 0.3]]),
 'b3': array([0.2, 0.1])}

In [5]:
def foward(x, network):
    a1 = np.dot(x, network['W1']) + network['b1']
    l1 = sigmoid(a1)
    a2 = np.dot(l1, network['W2']) + network['b2']
    l2 = sigmoid(a2)
    l3 = np.dot(l2, network['W3']) + network['b3']
    
    y = identity_func(l3)
    
    return y

In [6]:
x = np.array([0.5, 0.6])
network = init_network()
foward(x, network)

array([0.9861679 , 0.72797112])

In [14]:
def softmax(a):
    # オーバーフローの恐れあり
    # y = np.exp(a) / np.sum(np.exp(a))
    
    c = np.max(a)
    y = np.exp(a-c) / np.sum(np.exp(a-c))
    return y

In [15]:
softmax(x)

array([0.47502081, 0.52497919])

In [ ]:
mnist_X, mnist_y = fetch_openml("mnist_784", version=1, return_X_y=True)

X = mnist_X.astype("float32").to_numpy()
y = mnist_y.astype(int).to_numpy()

# 学習用と評価用に分割
X_train, X_test, t_train, t_test = train_test_split(X, y, test_size=10000)

In [31]:
import pickle
with open('mnist_X.pkl', 'wb') as f:
    pickle.dump(X, f)
with open('mnist_y.pkl', 'wb') as f:
    pickle.dump(y, f)

In [5]:
t_train

array([1, 6, 1, ..., 6, 9, 3])

In [2]:
from dataset.mnist import load_mnist

In [3]:
X_train, X_test, t_train, t_test = load_mnist('dataset')