In [11]:
import torch
import numpy as np

In [21]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
torch.zeros((2,3))

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [15]:
np.array([[1, 2, 3], [4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
torch.tensor([[1, 2, 3], [4, 5, 6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [17]:
np.array([[1, 2, 3], [4, 5, 6]]).dtype

dtype('int64')

In [18]:
torch.tensor([[1, 2, 3], [4, 5, 6]]).dtype

torch.int64

In [27]:
torch.ones((2, 3), dtype=torch.int64)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [37]:
a = torch.zeros(2)

In [29]:
a

tensor([0., 0.])

In [32]:
a.add_(2)

tensor([2., 2.])

In [35]:
a.add_(19)

tensor([21., 21.])

In [36]:
a

tensor([21., 21.])

In [41]:
torch.from_numpy(np.ones((2, 3)))

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [43]:
x = torch.tensor(1.0, requires_grad=True)
a, b = 3, 5
y = a*x + b

In [44]:
y

tensor(8., grad_fn=<AddBackward0>)

In [45]:
y.backward()

In [46]:
x.grad

tensor(3.)

In [48]:
v = torch.tensor(1.0, requires_grad=True)
w = torch.tensor(1.0, requires_grad=True)
a, b, c = 4, 6, 1

out = a*v + b*w + c

In [50]:
out.backward()

In [53]:
print(v.grad)
print(w.grad)

tensor(4.)
tensor(6.)


In [60]:
a = torch.rand((2, 3))
a

tensor([[0.3894, 0.7042, 0.0705],
        [0.6767, 0.8276, 0.2827]])

In [62]:
b = a.zero_()
print(b)
print(a)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
