In [36]:
import numpy as np
import torch
from torch import nn
from torch.nn import functional as F
from torch import optim
from torchvision.models import vgg11

In [32]:
fc = nn.Linear(4, 2)
x = torch.Tensor([1.0, 2.0, 3.0, 4.0])

y = fc(x)
print(y)


tensor([-2.6134, -0.5825], grad_fn=<ViewBackward0>)


In [33]:
F.relu(y)

tensor([0., 0.], grad_fn=<ReluBackward0>)

In [34]:
criterion = nn.MSELoss()

x = torch.Tensor([0, 1, 2])
y = torch.Tensor([1, -1, 0])

loss = criterion(x, y)
loss

tensor(3.)

In [38]:
model = vgg11()

optimizer = optim.Adam(model.parameters())
print(optimizer)

Adam (
Parameter Group 0
    amsgrad: False
    betas: (0.9, 0.999)
    capturable: False
    differentiable: False
    eps: 1e-08
    foreach: None
    fused: None
    lr: 0.001
    maximize: False
    weight_decay: 0
)


In [41]:
class mlp_net(nn.Module):
    def __init__(self):
        super().__init__()
        
        self.fc1 = nn.Linear(3, 5)
        self.fc2 = nn.Linear(5, 2)
        
        self.criterion = nn.MSELoss()
        self.optimizer = optim.Adam(self.parameters())
        
    def forward(self, x):
        x = self.fc1(x)
        print(f"fc1を通過`{x}")      
        x = F.relu(x)
        print(f"reluを通過`{x}")   
        x = self.fc2(x)
        return x        
    

In [42]:
model = mlp_net()

x = torch.Tensor([0, 1, 2])

output = model(x)
output

fc1を通過`tensor([-0.6480,  1.1148, -0.0161,  0.5720,  0.9670], grad_fn=<ViewBackward0>)
reluを通過`tensor([0.0000, 1.1148, 0.0000, 0.5720, 0.9670], grad_fn=<ReluBackward0>)


tensor([-0.2800, -0.7395], grad_fn=<ViewBackward0>)